import type { PointTransaction, User } from "./types";

export const MOCK_USERS: User[] = [
  {
    id: "1",
    name: "Alex Rivera",
    email: "alex.r@example.com",
    role: "user",
    tier: 3,
    legacyPoints: 1250,
    activePoints: 450,
    totalSpent: 1240.5,
    totalEarned: 2450,
    joinDate: "2024-01-15",
    lastActive: "2024-04-28",
    status: "active",
    location: "Singapore",
  },
  {
    id: "2",
    name: "Sarah Chen",
    email: "sarah.c@example.com",
    role: "partner",
    tier: 2,
    legacyPoints: 840,
    activePoints: 120,
    totalSpent: 450,
    totalEarned: 890.2,
    joinDate: "2024-02-10",
    lastActive: "2024-04-27",
    status: "active",
    location: "Hong Kong",
  },
  {
    id: "3",
    name: "Marcus Thorne",
    email: "m.thorne@example.com",
    role: "user",
    tier: 1,
    legacyPoints: 150,
    activePoints: 45,
    totalSpent: 25,
    totalEarned: 150,
    joinDate: "2024-03-05",
    lastActive: "2024-04-20",
    status: "suspended",
    location: "London",
  },
  {
    id: "4",
    name: "Elena Vance",
    email: "vance.e@example.com",
    role: "partner",
    tier: 3,
    legacyPoints: 3400,
    activePoints: 2100,
    totalSpent: 5600,
    totalEarned: 12400,
    joinDate: "2023-11-20",
    lastActive: "2024-04-28",
    status: "active",
    location: "New York",
  },
  {
    id: "5",
    name: "David Kim",
    email: "d.kim@example.com",
    role: "user",
    tier: 2,
    legacyPoints: 420,
    activePoints: 85,
    totalSpent: 120,
    totalEarned: 340.5,
    joinDate: "2024-03-15",
    lastActive: "2024-04-25",
    status: "active",
    location: "Seoul",
  },
];

export const TIER_CHART_DATA = [
  { month: "Nov", score: 10 },
  { month: "Dec", score: 25 },
  { month: "Jan", score: 45 },
  { month: "Feb", score: 40 },
  { month: "Mar", score: 65 },
  { month: "Apr", score: 85 },
];

export const POINT_HISTORY: PointTransaction[] = [
  {
    id: "t1",
    date: "2024-04-25",
    amount: 100,
    reason: "Beta Testing Feedback",
    type: "earned",
  },
  {
    id: "t2",
    date: "2024-04-22",
    amount: -50,
    reason: "Marketplace Item: Pro Icon Pack",
    type: "spent",
  },
  {
    id: "t3",
    date: "2024-04-15",
    amount: 250,
    reason: "Manual Correction",
    adminName: "Admin Jo",
    type: "adjustment",
  },
  {
    id: "t4",
    date: "2024-04-10",
    amount: 500,
    reason: "Founding Member Bonus",
    type: "earned",
  },
];
