import type { MyEvent } from "~/features/workspace/types/my-events";

/**
 * Stand-in for the creator's events until the events endpoint is wired up.
 * The loader filters and pages over this list so the page behaves exactly as
 * it will once `MY_EVENTS` is swapped for the API response.
 */
export const MY_EVENTS: MyEvent[] = [
  {
    id: "global-wellness-session",
    title: "Global Wellness Session",
    description:
      "A guided evening of movement, breathwork and community for anyone who needs a reset.",
    category: "Wellness",
    coverImageKey: "/images/background.jpg",
    status: "LIVE",
    format: "HYBRID",
    startAt: "2026-09-12T08:00:00+07:00",
    endAt: "2026-09-12T11:00:00+07:00",
    venue: "Virtual Event",
    currencyCode: "USD",
    revenue: 1200,
    ticketsSold: 342,
    ticketCapacity: 600,
    attendanceCount: 318,
  },
  {
    id: "cambodia-creator-summit",
    title: "Cambodia Creator Summit",
    description:
      "Two days of talks and workshops with the storytellers shaping Khmer culture online.",
    category: "Conference",
    coverImageKey: "/images/hero-background-image.webp",
    status: "PUBLISHED",
    format: "IN_PERSON",
    startAt: "2026-10-04T09:00:00+07:00",
    endAt: "2026-10-05T17:00:00+07:00",
    venue: "Factory Phnom Penh",
    currencyCode: "USD",
    revenue: 4850,
    ticketsSold: 194,
    ticketCapacity: 400,
    attendanceCount: null,
  },
  {
    id: "khmer-craft-night",
    title: "Khmer Craft Night",
    description:
      "Hands-on weaving and lacquer sessions led by artisans from Siem Reap province.",
    category: "Workshop",
    coverImageKey: "/images/Inspiration.jpg",
    status: "DRAFT",
    format: "IN_PERSON",
    startAt: "2026-11-21T18:00:00+07:00",
    endAt: null,
    venue: "To be announced",
    currencyCode: "USD",
    revenue: 0,
    ticketsSold: 0,
    ticketCapacity: null,
    attendanceCount: null,
  },
  {
    id: "cambodia-global-virtual-launch",
    title: "Cambodia Global Virtual Launch 2025",
    description:
      "The launch broadcast that introduced True Khmer's community programmes worldwide.",
    category: "Conference",
    coverImageKey: "/images/registerBG2.webp",
    status: "ENDED",
    format: "ONLINE",
    startAt: "2026-03-12T08:00:00+07:00",
    endAt: "2026-03-12T10:30:00+07:00",
    venue: "Virtual Event",
    currencyCode: "USD",
    revenue: 100,
    ticketsSold: 90,
    ticketCapacity: 100,
    attendanceCount: 90,
  },
  {
    id: "young-founders-mixer",
    title: "Young Founders Mixer",
    description:
      "An informal evening connecting first-time founders with mentors and early investors.",
    category: "Networking",
    coverImageKey: "/images/volunteer-header-background.webp",
    status: "CANCELLED",
    format: "IN_PERSON",
    startAt: "2026-05-30T18:30:00+07:00",
    endAt: "2026-05-30T21:00:00+07:00",
    venue: "Raintree, Phnom Penh",
    currencyCode: "USD",
    revenue: 0,
    ticketsSold: 0,
    ticketCapacity: 120,
    attendanceCount: null,
  },
  {
    id: "digital-skills-bootcamp",
    title: "Digital Skills Bootcamp",
    description:
      "A four-week evening bootcamp covering the basics of design, data and storytelling.",
    category: "Training",
    coverImageKey: "/images/forum-avatar.jpg",
    status: "PUBLISHED",
    format: "ONLINE",
    startAt: "2026-09-28T19:00:00+07:00",
    endAt: "2026-10-26T21:00:00+07:00",
    venue: "Virtual Event",
    currencyCode: "USD",
    revenue: 760,
    ticketsSold: 38,
    ticketCapacity: 80,
    attendanceCount: null,
  },
];
