name: Stage Deployment

on:
  push:
    branches: [develop]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout V3
        uses: actions/checkout@v3

      - name: Build and Push
        run: curl -s -L https://dokploy-build-loffy-api.bongit.net/0jdwMy_oOCIUhYjEEr3Pz | bash
      - name: Deploy to Dokploy
        run: |
          curl --request GET 'https://dokploy.bongit.net/api/deploy/-grOIaoT0mxC0unbi8Cg4'
